# Generated by Django 4.2.7 on 2023-11-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_playerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
