# Generated by Django 4.2.7 on 2023-11-18 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_player_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='password',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='matches_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='matches_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='rank',
            field=models.CharField(default='Iron', max_length=255),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.player', to_field='username'),
        ),
    ]
