# Generated by Django 4.2.7 on 2023-11-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_playerprofile_email_remove_playerprofile_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerProfile',
        ),
    ]
