# Generated by Django 4.2.7 on 2023-11-18 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_delete_playerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.player', to_field='username')),
                ('level', models.IntegerField(default=1)),
                ('rank', models.CharField(default='Iron', max_length=255)),
                ('games_played', models.IntegerField(default=0)),
                ('matches_won', models.IntegerField(default=0)),
                ('matches_lost', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'PlayerProfile',
            },
        ),
    ]
