# Generated by Django 4.2.7 on 2023-11-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_playerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerProfile',
        ),
    ]
