# Generated by Django 4.2.7 on 2023-11-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_playerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='matches_won_curr_lvl',
            field=models.IntegerField(default=0),
        ),
    ]
